language: c

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y gcc-multilib     # support CC=gcc   ARCH=x86
    - sudo apt-get install -y gcc-4.6-multilib # support CC=clang ARCH=x86

compiler:
    - gcc
    - clang

env:
    - ARCH=x64 TEST=user-interface.sh
    - ARCH=x86 TEST=user-interface.sh

    - ARCH=x64 TEST=makefile.sh
    - ARCH=x86 TEST=makefile.sh

script:
    - ./test/run.sh
